# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kN3WDysqydVR7T_7yEjDS7J5zeFK4iOX
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

df=pd.read_excel("Telco_Churn_Dirty (1).xlsx")
df

df.rename(columns={
    "Location ID": "Location_id",
    "Customer ID": "customer_id",
    "Zip Code": "Zip_code",},inplace=True)
df

df.isnull().sum()

df = df.dropna(subset=['customer_id'])

df['Zip_code'].fillna(df['Zip_code'].mode()[0], inplace=True)

df['Latitude'].fillna(df['Latitude'].median(), inplace=True)

df['Longitude'].fillna(df['Longitude'].median(), inplace=True)

df.duplicated().sum()

df = df.drop_duplicates()

text_cols = df.select_dtypes(include='object').columns
for col in text_cols:
    df[col] = df[col].str.strip()

df

df.describe()

df['City']=df['City'].str.rstrip('*&#@')
df

pd.set_option('display.max.rows', None)
df

df['City'] = df['City'].str.replace('#', ' ', regex=False)
df

df['City'] = df['City'].str.title()
df

df['City']=df['City'].str.rstrip('99')
df

df['Zip_code'] = df['Zip_code'].astype(str).str.replace(r'[^0-9]', '', regex=True)
df

df['City'] = df['City'].astype(str).str.strip().str.title()
df

df[['Latitude', 'Longitude']].describe()

df[['Latitude', 'Longitude']].isnull().sum()

df.loc[(df['Latitude'] < -90) | (df['Latitude'] > 90), 'Latitude'] = np.nan

df.loc[(df['Longitude'] < -180) | (df['Longitude'] > 180), 'Longitude'] = np.nan

df.to_excel("Telco_Churn_Clean.xlsx", index=False)

from google.colab import files

files.download("Telco_Churn_Clean.xlsx")

